title: Cedar Grove Christian
description: A warm, inviting local church where everyone is welcome and God comes first.
plugins:
  - jekyll-seo-tag
markdown: kramdown
theme: minima
exclude:
  - node_modules
  - vendor
  - README.md
  - package.json

  # Site data used in templates
service_times:
  sunday_service: "9:30 AM"
  sunday_school: "10:30 AM"
  wednesday_bible_study: "6:30 PM"
address: "5270 Chuckey Pike, Chuckey, TN 37641"
email: "cedargrovechristiantn@gmail.com"
phone: "423-525-7413"
facebook: "https://www.facebook.com/profile.php?id=100064446712278"
youtube: "https://www.youtube.com/@CedarGroveChristian"